import {NgModule} from "@angular/core";
import { MatFileUploadModule } from 'angular-material-fileupload';
import { 
    MatMenuModule, 
    MatProgressSpinnerModule, 
    MatNativeDateModule, 
    MatInputModule, 
    MatButtonModule, 
    MatSelectModule, 
    MatIconModule, 
    MatToolbarModule, 
    MatSidenavModule, 
    MatListModule, 
    MatDatepickerModule, 
    MatCardModule,
    MatCheckboxModule,
    MatGridListModule,
    MatTabsModule,
    MatTooltipModule,
} from '@angular/material';

@NgModule({
imports: [
    MatMenuModule, 
    MatProgressSpinnerModule, 
    MatNativeDateModule, 
    MatInputModule, 
    MatButtonModule, 
    MatSelectModule, 
    MatIconModule, 
    MatToolbarModule, 
    MatSidenavModule, 
    MatListModule, 
    MatDatepickerModule, 
    MatCardModule,
    MatCheckboxModule,
    MatGridListModule,
    MatFileUploadModule,
    MatTabsModule,
    MatTooltipModule,
],
exports: [
    MatMenuModule, 
    MatProgressSpinnerModule, 
    MatNativeDateModule, 
    MatInputModule, 
    MatButtonModule, 
    MatSelectModule, 
    MatIconModule, 
    MatToolbarModule, 
    MatSidenavModule, 
    MatListModule, 
    MatDatepickerModule, 
    MatCardModule,
    MatCheckboxModule,
    MatGridListModule,
    MatFileUploadModule,
    MatTabsModule,
    MatTooltipModule,
],
})
export class CustomMaterialModule { }